name: story_vista
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter:
    sdk: flutter
  gap: ^3.0.1
  syncfusion_flutter_pdfviewer: ^24.1.44
  image_picker: ^1.0.7
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  google_sign_in: ^6.2.1
  firebase_auth: ^4.16.0
  shared_preferences: ^2.2.2
  file_picker: ^6.1.1
  uuid: ^4.3.3
  firebase_storage: ^11.6.0

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/
    - assets/png/
    - assets/svg/
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
